### ISSUE TITLE
Great project!!

### ISSUE THREAD

**Issue by MrinmoyHaloi** [0x454d505459/tornado#1]
Great project. Really looking forward to it. Community is the key to open source. I really love to see community making such things. I would like to ask you if you are looking forward to merge this project into the official Swirl programming language.
Thanks. Have a great day

**Comment by 0x4c756e61** [comment]
You know what unofficial mean right ?

**Comment by MrinmoyHaloi** [comment]
> You know what unofficial mean right ?

yes, i wanna make it official
